debug

diff --git a/.github/workflows/pr_ci.yml b/.github/workflows/pr_ci.yml
--- a/.github/workflows/pr_ci.yml
+++ b/.github/workflows/pr_ci.yml
@@ -40,7 +40,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       validate_paths: ${{ steps.format.outputs.dir_diff }}
-      plan_paths: ${{ steps.deps.outputs.examples }}
+      plan_paths: ${{ steps.format.outputs.plan_paths }}
       changed_files: ${{ steps.format.outputs.files_diff }}
     steps:
       - name: checkout code
@@ -57,57 +57,112 @@ jobs:
             modules/**/*.tf
             examples/**/*.tf
 
-      - name: extract only changed folders
+      - name: show raw DIFF
+        env:
+          DIFFS: ${{ steps.diff.outputs.all_changed_files }}
+        shell: bash
+        run: |
+          echo $DIFFS
+
+      - name: extract paths for tasks
         id: format
         env:
           DIFFS: ${{ steps.diff.outputs.all_changed_files }}
         shell: bash
         run: |
-          echo "dir_diff=$(echo -n "$DIFFS" | tr -d '\n' | tr '@' '\n' | sed -E "s/^(modules|examples)\/(.+)\/.*$/\1\/\2/" | sort -u | tr '\n' ',' | rev | cut -c2- | rev)" >> $GITHUB_OUTPUT
-          echo "files_diff=$(echo "$DIFFS" | tr '@' ' ')" >> $GITHUB_OUTPUT
 
-      - name: discover module->example dependencies
-        id: deps
-        env:
-          DIFFS: ${{ steps.format.outputs.dir_diff }}
-        shell: bash
-        run: |
-          if [ "$DIFFS" ]; then
-            EXAMPLES_DISCOVERY=$(for M in $(echo "$DIFFS" | tr '@' '\n' | grep modules); do
-              echo $(grep -rl "$M" examples/*/*.tf | sed -E "s/^(examples\/.*)\/.*$/\1/g")
-            done | sort -u | awk NF)
+          set -o pipefail
+          # build an array from the DIFFS input
+          DIFFS_ARRAY=(${DIFFS//@/ })
 
-            if [ "$(echo "$(echo $EXAMPLES_DISCOVERY | tr ' ' ','),$DIFFS" | grep examples)" ]; then
-              EXAMPLES_COMBINED=$(echo "$(echo $EXAMPLES_DISCOVERY | tr ' ' ','),$DIFFS" | tr ',' '\n' | awk NF | grep examples | sort -u)
-              echo "examples=$(echo -n $EXAMPLES_COMBINED | tr ' ' ',')" >> $GITHUB_OUTPUT
-            fi
-          fi
+          # extract folder names from DIFFS
+          DIRS=()
+          for ELEMENT in ${DIFFS_ARRAY[*]}; do
+            DIRS+=($(echo $ELEMENT | sed -E "s/^(modules|examples)\/(.+)\/.*$/\1\/\2/" ))
+          done
+
+          # from folders array extract only modules paths
+          ## double subshell here is to hide grep returning 1 when no modules paths are present in $DIRS
+          IFS=$'\n' DIFF_MODULES_ARRAY=($(echo $(grep modules <<< "${DIRS[*]}")))
+          unset IFS
+          echo DIFF_MODULES_ARRAY ${DIFF_MODULES_ARRAY[*]}
+          # use these paths to discover dependencies - find examples using modules from the list
+          EXAMPLES_DISCOVERED=()
+          for ELEMENT in ${DIFF_MODULES_ARRAY[*]}; do
+            EXAMPLES_DISCOVERED+=($(echo $(grep -rl "$ELEMENT" examples/*/*.tf | sed -E "s/^(examples\/.*)\/.*$/\1/g")))
+          done
+          echo EXAMPLES_DISCOVERED ${EXAMPLES_DISCOVERED[*]}
+          # deduplicate list of example paths
+          IFS=$'\n' EXAMPLES_DISCOVERED_DEDUPLICATED=($(sort -u <<<  "${EXAMPLES_DISCOVERED[*]}"))
+          unset IFS
+          echo EXAMPLES_DISCOVERED_DEDUPLICATED ${EXAMPLES_DISCOVERED_DEDUPLICATED[*]}
+          # create a combined list of folders containin original paths + discovered dependencies
+          COMBINED_FOLDERS=(${EXAMPLES_DISCOVERED_DEDUPLICATED[*]} ${DIRS[*]})
+          # deduplicate examples from the list
+          IFS=$'\n' COMBINED_FOLDERS_DEDUPLICATED=($(sort -u <<<  "${COMBINED_FOLDERS[*]}"))
+          unset IFS
+          echo COMBINED_FOLDERS_DEDUPLICATED ${COMBINED_FOLDERS_DEDUPLICATED[*]}
+          # extract only examples from the deduplicated list
+          IFS=$'\n' PLAN_DIRS=($(echo $(grep examples <<< "${COMBINED_FOLDERS_DEDUPLICATED[*]}")))
+          unset IFS
+          echo PLAN_DIRS ${PLAN_DIRS[*]}
+
+          DIR_DIFF=$(echo ${DIRS[*]} | tr ' ' ',')
+          PLAN_PATHS=$(echo ${PLAN_DIRS[*]} | tr ' ' ',')
+          echo PLAN_PATHS $PLAN_PATHS
+
+          # a list of chagned paths, used for validation tasks
+          echo "dir_diff=$DIR_DIFF" >> $GITHUB_OUTPUT
+          echo
+          # a list of changed files, used for pre-commit tasks
+          echo "files_diff=${DIFFS_ARRAY[*]}" >> $GITHUB_OUTPUT
+          echo
+          # a list of affected and changed examples, used for plan/apply tasks
+          echo "plan_paths=$PLAN_PATHS" >> $GITHUB_OUTPUT
+          echo
+
+  # debugger:
+  #   name: debug outputs
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - tf_prereqs
+  #   steps:
+  #     - name: runner
+  #       env:
+  #         # changed_files: ${{ needs.tf_prereqs.outputs.changed_files }}
+  #         # validate_paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
+  #         plan_paths: ${{ needs.tf_prereqs.outputs.plan_paths }}
+  #       shell: bash
+  #       run: |
+  #         # echo "changed_files: $changed_files"
+  #         # echo "validate_paths: $validate_paths"
+  #         echo "plan_paths: $plan_paths"
+
+  # pre_commit:
+  #   name: Pre-Commit
+  #   needs: [tf_prereqs]
+  #   if: ${{ needs.tf_prereqs.outputs.changed_files != '' }}
+  #   uses: ./.github/workflows/_pre_commit.yml
+  #   with:
+  #     pre-commit-hooks: ${{ inputs.pre-commit-hooks }}
+  #     pre-commit-files: ${{ needs.tf_prereqs.outputs.changed_files }}
 
 
-  pre_commit:
-    name: Pre-Commit
-    needs: [tf_prereqs]
-    if: ${{ needs.tf_prereqs.outputs.changed_files != '' }}
-    uses: ./.github/workflows/_pre_commit.yml
-    with:
-      pre-commit-hooks: ${{ inputs.pre-commit-hooks }}
-      pre-commit-files: ${{ needs.tf_prereqs.outputs.changed_files }}
-
-
-  validate:
-    name: validate all changed modules
-    needs: [tf_prereqs]
-    if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
-    uses: ./.github/workflows/_tf_validate.yml
-    with:
-      tf_version: ${{ inputs.tf_version }}
-      paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
+  # validate:
+  #   name: validate all changed modules
+  #   needs: [tf_prereqs]
+  #   if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
+  #   uses: ./.github/workflows/_tf_validate.yml
+  #   with:
+  #     tf_version: ${{ inputs.tf_version }}
+  #     paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
 
 
   plan_apply:
     name: run plan changed examples and dependencies
     needs: 
-      - validate
+      # - validate
+      - tf_prereqs
     if: ${{ needs.tf_prereqs.outputs.plan_paths != '' }}
     uses: ./.github/workflows/_tf_plan_apply.yml
     permissions:
@@ -123,20 +178,20 @@ jobs:
     secrets: inherit
 
 
-  branch_protection_junction:
-    name: junction point for branch protection
-    needs:
-      - validate
-      - pre_commit
-      - plan_apply
-    if: always()
-    permissions:
-      actions: read
-    runs-on: ubuntu-latest
-    steps:
-      - name: check statuses of other jobs
-        uses: technote-space/workflow-conclusion-action@v3
+  # branch_protection_junction:
+  #   name: junction point for branch protection
+  #   needs:
+  #     - validate
+  #     - pre_commit
+  #     - plan_apply
+  #   if: always()
+  #   permissions:
+  #     actions: read
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: check statuses of other jobs
+  #       uses: technote-space/workflow-conclusion-action@v3
 
-      - name: branch protection check validation point
-        run: | 
-          if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
+  #     - name: branch protection check validation point
+  #       run: | 
+  #         if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
