add max pararel to validation

diff --git a/.github/workflows/pr_ci.yml b/.github/workflows/pr_ci.yml
--- a/.github/workflows/pr_ci.yml
+++ b/.github/workflows/pr_ci.yml
@@ -12,7 +12,7 @@ on:
         description: When set to true runs also apply
         type: boolean
         default: false
-      indepotency:
+      idempotence:
         description: When set to true runs plan to on already applied configuration
         type: boolean
         default: true
@@ -57,12 +57,12 @@ jobs:
             modules/**/*.tf
             examples/**/*.tf
 
-      - name: show raw DIFF
-        env:
-          DIFFS: ${{ steps.diff.outputs.all_changed_files }}
-        shell: bash
-        run: |
-          echo $DIFFS
+      # - name: show raw DIFF
+      #   env:
+      #     DIFFS: ${{ steps.diff.outputs.all_changed_files }}
+      #   shell: bash
+      #   run: |
+      #     echo $DIFFS
 
       - name: extract paths for tasks
         id: format
@@ -133,30 +133,31 @@ jobs:
   #         # echo "validate_paths: $validate_paths"
   #         echo "plan_paths: $plan_paths"
 
-  pre_commit:
-    name: Pre-Commit
-    needs: [tf_prereqs]
-    if: ${{ needs.tf_prereqs.outputs.changed_files != '' }}
-    uses: ./.github/workflows/_pre_commit.yml
-    with:
-      pre-commit-hooks: ${{ inputs.pre-commit-hooks }}
-      pre-commit-files: ${{ needs.tf_prereqs.outputs.changed_files }}
+  # pre_commit:
+  #   name: Pre-Commit
+  #   needs: [tf_prereqs]
+  #   if: ${{ needs.tf_prereqs.outputs.changed_files != '' }}
+  #   uses: ./.github/workflows/_pre_commit.yml
+  #   with:
+  #     pre-commit-hooks: ${{ inputs.pre-commit-hooks }}
+  #     pre-commit-files: ${{ needs.tf_prereqs.outputs.changed_files }}
 
 
-  validate:
-    name: validate all changed modules
-    needs: [tf_prereqs]
-    if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
-    uses: ./.github/workflows/_tf_validate.yml
-    with:
-      tf_version: ${{ inputs.tf_version }}
-      paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
+  # validate:
+  #   name: validate all changed modules
+  #   needs: [tf_prereqs]
+  #   if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
+  #   uses: ./.github/workflows/_tf_validate.yml
+  #   with:
+  #     tf_version: ${{ inputs.tf_version }}
+  #     paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
+  #     max_parallel: ${{ inputs.max_parallel }}
 
 
   plan_apply:
     name: run plan changed examples and dependencies
     needs: 
-      - validate
+      # - validate
       - tf_prereqs
     if: ${{ needs.tf_prereqs.outputs.plan_paths != '' }}
     uses: ./.github/workflows/_tf_plan_apply.yml
@@ -168,25 +169,25 @@ jobs:
       tf_version: ${{ inputs.tf_version }}
       paths: ${{ needs.tf_prereqs.outputs.plan_paths }}
       do_apply: ${{ inputs.do_apply }}
-      indepotency: ${{ inputs.indepotency }}
+      idempotence: ${{ inputs.idempotence }}
       max_parallel: ${{ inputs.max_parallel }}
     secrets: inherit
 
 
-  branch_protection_junction:
-    name: junction point for branch protection
-    needs:
-      - validate
-      - pre_commit
-      - plan_apply
-    if: always()
-    permissions:
-      actions: read
-    runs-on: ubuntu-latest
-    steps:
-      - name: check statuses of other jobs
-        uses: technote-space/workflow-conclusion-action@v3
+  # branch_protection_junction:
+  #   name: junction point for branch protection
+  #   needs:
+  #     - validate
+  #     - pre_commit
+  #     - plan_apply
+  #   if: always()
+  #   permissions:
+  #     actions: read
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: check statuses of other jobs
+  #       uses: technote-space/workflow-conclusion-action@v3
 
-      - name: branch protection check validation point
-        run: | 
-          if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
+  #     - name: branch protection check validation point
+  #       run: | 
+  #         if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
