simply for tests

diff --git a/.github/workflows/pr_ci.yml b/.github/workflows/pr_ci.yml
--- a/.github/workflows/pr_ci.yml
+++ b/.github/workflows/pr_ci.yml
@@ -28,14 +28,14 @@ on:
         required: true
 
 jobs:
-  pre_commit:
-    name: Pre-Commit
-    uses: ./.github/workflows/_pre_commit.yml
+  # pre_commit:
+  #   name: Pre-Commit
+  #   uses: ./.github/workflows/_pre_commit.yml
 
 
-  checkov:
-    name: Checkov
-    uses: ./.github/workflows/_checkov.yml
+  # checkov:
+  #   name: Checkov
+  #   uses: ./.github/workflows/_checkov.yml
 
 
   tf_prereqs:
@@ -84,21 +84,21 @@ jobs:
           fi
 
 
-  validate:
-    name: validate all changed modules
-    needs: [tf_prereqs]
-    if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
-    uses: ./.github/workflows/_tf_validate.yml
-    with:
-      tf_version: ${{ inputs.tf_version }}
-      paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
+  # validate:
+  #   name: validate all changed modules
+  #   needs: [tf_prereqs]
+  #   if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
+  #   uses: ./.github/workflows/_tf_validate.yml
+  #   with:
+  #     tf_version: ${{ inputs.tf_version }}
+  #     paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
 
 
   plan_apply:
     name: run plan changed examples and dependencies
     needs: 
       - tf_prereqs
-      - validate
+      # - validate
     if: ${{ needs.tf_prereqs.outputs.plan_paths != '' }}
     uses: ./.github/workflows/_tf_plan_apply.yml
     permissions:
@@ -114,21 +114,21 @@ jobs:
     secrets: inherit
 
 
-  branch_protection_junction:
-    name: junction point for branch protection
-    needs:
-      - validate
-      - pre_commit
-      - checkov
-      - plan_apply
-    if: always()
-    permissions:
-      actions: read
-    runs-on: ubuntu-latest
-    steps:
-      - name: check statuses of other jobs
-        uses: technote-space/workflow-conclusion-action@v3
+  # branch_protection_junction:
+  #   name: junction point for branch protection
+  #   needs:
+  #     - validate
+  #     - pre_commit
+  #     - checkov
+  #     - plan_apply
+  #   if: always()
+  #   permissions:
+  #     actions: read
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: check statuses of other jobs
+  #       uses: technote-space/workflow-conclusion-action@v3
 
-      - name: branch protection check validation point
-        run: | 
-          if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
+  #     - name: branch protection check validation point
+  #       run: | 
+  #         if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
