add plan prereqs

diff --git a/.github/workflows/pr_ci.yml b/.github/workflows/pr_ci.yml
--- a/.github/workflows/pr_ci.yml
+++ b/.github/workflows/pr_ci.yml
@@ -7,14 +7,14 @@ on:
   workflow_call:
 
 jobs:
-  pre-commit:
-    name: Pre-Commit
-    uses: ./.github/workflows/_pre_commit.yml
+  # pre-commit:
+  #   name: Pre-Commit
+  #   uses: ./.github/workflows/_pre_commit.yml
 
 
-  checkov:
-    name: Checkov
-    uses: ./.github/workflows/_checkov.yml
+  # checkov:
+  #   name: Checkov
+  #   uses: ./.github/workflows/_checkov.yml
 
 
   tf_prereqs:
@@ -22,7 +22,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       validate_paths: ${{ steps.format.outputs.dir_diff }}
-      # plan_paths: ${{ steps.deps.outputs.examples }}
+      plan_paths: ${{ steps.deps.outputs.examples }}
     steps:
       - name: checkout code
         uses: actions/checkout@v3
@@ -45,37 +45,43 @@ jobs:
         run: |
           echo "::set-output name=dir_diff::$(echo -n "$DIFFS" | sed -E "s/^(modules|examples)\/(.+)\/.*$/\1\/\2/"  | tr '\n' ',')"
 
-      # - name: discover module->example dependencies
-      #   id: deps
-      #   env:
-      #     DIFFS: ${{ steps.format.outputs.dir_diff }}
-      #   shell: bash
-      #   run: |
-      #     if [ "$DIFFS" ]; then
-      #       EXAMPLES_DISCOVERY=$(for M in $(echo "$DIFFS" | tr ',' '\n' | grep modules); do
-      #         echo $(grep -rl "$M" examples/*/*.tf | sed -E "s/^(examples\/.*)\/.*$/\1/g")
-      #       done | sort -u | awk NF)
+      - name: discover module->example dependencies
+        id: deps
+        env:
+          DIFFS: ${{ steps.format.outputs.dir_diff }}
+        shell: bash
+        run: |
+          if [ "$DIFFS" ]; then
+            EXAMPLES_DISCOVERY=$(for M in $(echo "$DIFFS" | tr ',' '\n' | grep modules); do
+              echo $(grep -rl "$M" examples/*/*.tf | sed -E "s/^(examples\/.*)\/.*$/\1/g")
+            done | sort -u | awk NF)
 
-      #       EXAMPLES_COMBINED=$(echo "$(echo $EXAMPLES_DISCOVERY | tr ' ' ','),$DIFFS" | tr ',' '\n' | awk NF | grep examples | sort -u)
+            EXAMPLES_COMBINED=$(echo "$(echo $EXAMPLES_DISCOVERY | tr ' ' ','),$DIFFS" | tr ',' '\n' | awk NF | grep examples | sort -u)
 
-      #       echo "::set-output name=examples::$(echo -n $EXAMPLES_COMBINED | jq -R -s -c 'split(" ")')"
-      #     fi
+            # echo "::set-output name=examples::$(echo -n $EXAMPLES_COMBINED | jq -R -s -c 'split(" ")')"
+            echo "::set-output name=examples::$(echo -n $EXAMPLES_COMBINED | tr ' ' ',')"
+          fi
 
 
-  validate:
-    name: validate all changed modules
-    needs: [tf_prereqs]
-    if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
-    uses: ./.github/workflows/_tf_validate.yml
-    with:
-      tf_version: 0.15 1.0 1.1 1.2 1.3
-      paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
+  # validate:
+  #   name: validate all changed modules
+  #   needs: [tf_prereqs]
+  #   if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
+  #   uses: ./.github/workflows/_tf_validate.yml
+  #   with:
+  #     tf_version: 0.15 1.0 1.1 1.2 1.3
+  #     paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
 
 
   # plan:
   #   name: '${{ matrix.path }}@${{ matrix.tf_version }}'
   #   needs: [tf_prereqs]
   #   if: ${{ needs.tf_prereqs.outputs.plan_paths != '' }}
+  #   uses: ./.github/workflows/_tf_plan.yml
+  #   with:
+  #     tf_version: 1.2 #0.15 1.0 1.1 1.2 1.3
+  #     paths: ${{ needs.tf_prereqs.outputs.validate_paths }}
+    
   #   strategy:
   #     matrix:
   #       path: ${{ fromJson(needs.tf_prereqs.outputs.plan_paths) }}
@@ -104,21 +110,21 @@ jobs:
   #         tf_version: ${{ matrix.tf_version }}
   #         # tf_version: '1.2'
 
-  branch_protection_junction:
-    name: junction point for branch protection
-    needs:
-      - validate
-      - pre-commit
-      - checkov
-      # - plan
-    if: always()
-    permissions:
-      actions: read
-    runs-on: ubuntu-latest
-    steps:
-      - name: check statuses of other jobs
-        uses: technote-space/workflow-conclusion-action@v3
+  # branch_protection_junction:
+  #   name: junction point for branch protection
+  #   needs:
+  #     - validate
+  #     - pre-commit
+  #     - checkov
+  #     # - plan
+  #   if: always()
+  #   permissions:
+  #     actions: read
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: check statuses of other jobs
+  #       uses: technote-space/workflow-conclusion-action@v3
 
-      - name: branch protection check validation point
-        run: | 
-          if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
+  #     - name: branch protection check validation point
+  #       run: | 
+  #         if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
